# See http://about.travis-ci.org/docs/user/build-configuration/
language: scala
scala:
  - 2.10.2
env: PYTHON_VER="`python -c 'import sys; print(sys.version_info[0])'`" NODE_ENV="0.10.22" RUBY_ENV='1.9.2' PY_ENV=2.2.2 DB=mongodb SBT_OPTS="-XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:PermSize=256M -XX:MaxPermSize=512M"
branches:
  only:
    - master
jdk:
  - oraclejdk7
services:
  - mongodb
